# Generated by Django 5.1.6 on 2025-03-19 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0003_add_initial_currencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetplan',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budgets.currency'),
        ),
    ]
